# Generated by Django 2.2.16 on 2021-12-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_auto_20211224_2048'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='one_following1',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='one_love'),
        ),
    ]
