# Generated by Django 2.2.16 on 2021-12-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_auto_20211224_2055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='authoe_author',
        ),
    ]
